# Services to monitor/inspect Open edX
version: "3.5"
services:
  adminer:
    image: adminer:4.7.6
    restart: unless-stopped
    container_name: adminer
    depends_on:
      - mysql
    networks:
      derex:
        aliases:
          - adminer.localhost

  portainer:
    image: portainer/portainer:1.21.0
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - derex_portainer_data:/data portainer/portainer
    container_name: portainer
    networks:
      derex:
        aliases:
          - portainer.localhost

volumes:
  derex_portainer_data:
    external: true

networks:
  derex:
    name: derex
