name: Build
on: [push]
jobs:
  Juniper:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."

  Koa:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."

  Lilac:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
